### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by Monk1mmmmm** [oleksandrblazhko/ai203-kurgan#5]
## Завдання 1
- Потреба: Друзі
- Задоволені умови: зрозумілість, цінність, актуальність
### Відповідь
- Зрозумілість: Потреба в друзях зрозуміла, логічна - бажання ділитись інформацією, спілкуватись з іншими людьми
- Цінність: Друзі - одна із базових потреб для людини, соціальної істоти.
- Актуальність: Друзі актуальні в усі часи, як в радощі, так і в смутку.

## Завдання 2
- **Feature: User Authorization**
Авторизація необхідна, аби кожен користувач мав особистий профіль, що відкриває можливість комунікацій між друзями, бо користувачі можуть одне одного ідентифікувати

- **Feature: Create a new category**
Дана функція дозволяє сортувати інформацію залежно від потреб у зацікавленості музикою, що спрощує задоволення потреби.

- **Feature: Create a discussion topic**
Функція теми для дискусії уособлює собою майданчик для обміну ідей музикальної спрямованості із друзями, що водночас забезпечує задоволення як зацікавленості музикою, так і потреби в друзях.

**Comment by oleksandrblazhko** [comment]
1) не прочитали це - (не плутати із задоволеністю реальною потребою)
Оцінка = 2 бали
